//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomAid.SPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxMessage
    {
        public int SysID { get; set; }
        public int MessageID { get; set; }
        public Nullable<int> PrevMessageID { get; set; }
        public int SenderID { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime SentDate { get; set; }
        public bool IsGeneral { get; set; }
    
        public virtual GeneralMessage GeneralMessage { get; set; }
        public virtual Invitation Invitation { get; set; }
    }
}
