//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomAid.SPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public int SysID { get; set; }
        public int MessageID { get; set; }
        public bool IsAccepted { get; set; }
    
        public virtual InboxMessage InboxMessage { get; set; }
    }
}
